### ISSUE TITLE
How can I build a 12.04 ubuntu i386 image on macOS ?

### ISSUE THREAD

**Issue by wenerme** [ioft/dockerhub#3]
I download the rootfs, and from scratch, but still got x86_64, do I have to build image on i386 to get i386 image ?

**Comment by umiddelb** [comment]
Which rootfs did you download? 
If you take the [32bit Ubuntu Core rootfs](http://cdimage.ubuntu.com/ubuntu-base/releases/12.04/release/ubuntu-base-12.04.4-core-i386.tar.gz), only 32bit packages will be subsequently installed. 
If you build the image on a x86_64 platform the image will be labelled as "Architecture": "amd64" (according to docker inspect), but still be executable on a i386 platform.

Beside of this, I won't recommend to build something new on top of 12.04. It is old as the hills and it contains a lot of open security issues, fixed in newer Ubuntu releases. What is the reason to pick 12.04?

**Comment by wenerme** [comment]
I need 12.04 to compile the old router kernel, in newer release, some dependence was broken, I use https://partner-images.canonical.com/core/precise/current/ubuntu-precise-core-cloudimg-i386-root.tar.gz , but uname still return  x86_64

```
FROM scratch
ADD ubuntu-precise-core-cloudimg-i386-root.tar.gz /

# a few minor docker-specific tweaks
# see https://github.com/docker/docker/blob/9a9fc01af8fb5d98b8eec0740716226fadb3735c/contrib/mkimage/debootstrap
RUN set -xe \
	\
# https://github.com/docker/docker/blob/9a9fc01af8fb5d98b8eec0740716226fadb3735c/contrib/mkimage/debootstrap#L40-L48
	&& echo '#!/bin/sh' > /usr/sbin/policy-rc.d \
	&& echo 'exit 101' >> /usr/sbin/policy-rc.d \
	&& chmod +x /usr/sbin/policy-rc.d \
	\
# https://github.com/docker/docker/blob/9a9fc01af8fb5d98b8eec0740716226fadb3735c/contrib/mkimage/debootstrap#L54-L56
	&& dpkg-divert --local --rename --add /sbin/initctl \
	&& cp -a /usr/sbin/policy-rc.d /sbin/initctl \
	&& sed -i 's/^exit.*/exit 0/' /sbin/initctl \
	\
# https://github.com/docker/docker/blob/9a9fc01af8fb5d98b8eec0740716226fadb3735c/contrib/mkimage/debootstrap#L71-L78
	&& echo 'force-unsafe-io' > /etc/dpkg/dpkg.cfg.d/docker-apt-speedup \
	\
# https://github.com/docker/docker/blob/9a9fc01af8fb5d98b8eec0740716226fadb3735c/contrib/mkimage/debootstrap#L85-L105
	&& echo 'DPkg::Post-Invoke { "rm -f /var/cache/apt/archives/*.deb /var/cache/apt/archives/partial/*.deb /var/cache/apt/*.bin || true"; };' > /etc/apt/apt.conf.d/docker-clean \
	&& echo 'APT::Update::Post-Invoke { "rm -f /var/cache/apt/archives/*.deb /var/cache/apt/archives/partial/*.deb /var/cache/apt/*.bin || true"; };' >> /etc/apt/apt.conf.d/docker-clean \
	&& echo 'Dir::Cache::pkgcache ""; Dir::Cache::srcpkgcache "";' >> /etc/apt/apt.conf.d/docker-clean \
	\
# https://github.com/docker/docker/blob/9a9fc01af8fb5d98b8eec0740716226fadb3735c/contrib/mkimage/debootstrap#L109-L115
	&& echo 'Acquire::Languages "none";' > /etc/apt/apt.conf.d/docker-no-languages \
	\
# https://github.com/docker/docker/blob/9a9fc01af8fb5d98b8eec0740716226fadb3735c/contrib/mkimage/debootstrap#L118-L130
	&& echo 'Acquire::GzipIndexes "true"; Acquire::CompressionTypes::Order:: "gz";' > /etc/apt/apt.conf.d/docker-gzip-indexes \
	\
# https://github.com/docker/docker/blob/9a9fc01af8fb5d98b8eec0740716226fadb3735c/contrib/mkimage/debootstrap#L134-L151
	&& echo 'Apt::AutoRemove::SuggestsImportant "false";' > /etc/apt/apt.conf.d/docker-autoremove-suggests

# delete all the apt list files since they're big and get stale quickly
RUN rm -rf /var/lib/apt/lists/*
# this forces "apt-get update" in dependent images, which is also good

# enable the universe
RUN sed -i 's/^#\s*\(deb.*universe\)$/\1/g' /etc/apt/sources.list

# make systemd-detect-virt return "docker"
# See: https://github.com/systemd/systemd/blob/aa0c34279ee40bce2f9681b496922dedbadfca19/src/basic/virt.c#L434
RUN mkdir -p /run/systemd && echo 'docker' > /run/systemd/container

# overwrite this with 'CMD []' in a dependent Dockerfile
CMD ["/bin/bash"]
```

**Comment by umiddelb** [comment]
`arch` and `uname` will tell you the truth, as you are running a 64 bit kernel. 

You might be happier running a chroot shell inside the 32 bit userland:

```
set -ex

mkdir -p rootfs

curl -sSL https://partner-images.canonical.com/core/precise/current/ubuntu-precise-core-cloudimg-i386-root.tar.gz | sudo tar --numeric-owner -xhpPzf - -C rootfs/

sudo mount -o bind /dev ./rootfs/dev
sudo mount -o bind /dev/pts ./rootfs/dev/pts
sudo mount -t sysfs /sys ./rootfs/sys
sudo mount -t proc /proc ./rootfs/proc
sudo cp /proc/mounts ./rootfs/etc/mtab
echo "nameserver 8.8.8.8" | sudo tee ./rootfs/etc/resolv.conf

sudo LC_ALL=C LANGUAGE=C LANG=C chroot ./rootfs bash
```

Inside the chroot environment you can install additional packages, like `gcc` and `make` and try to build your router kernel. You can access all files from the outside and re-enter the chroot shell as often as you want, all changes are persistent. 

Are the kernel sources available to the public? If the build systems strongly depends on i386 arch (sometimes it's only an environment variable you can override) you might end up installing Ubuntu 12.04 in a virtual machine instead.

**Comment by wenerme** [comment]
Kernel is here https://github.com/comcat/miwifi , the tool seems require i386 and only tested on ubuntu 12.04. 

If this still not work, I will setup a vm.

**Comment by umiddelb** [comment]
I've cloned the repository and now `make` is about to build a kernel ...

**Comment by umiddelb** [comment]
kernel is ready, now make composes the rootfs ...

**Comment by umiddelb** [comment]
```
The rootfs jarvis-rootfs.tgz is generated
-----------------------------------------------------
 Kernel image and rootfs of Xiaomi R1D is generated.
 Kernel image vmlinuz is located at current directory
 The rootfs is located at rootfs/
-----------------------------------------------------
```

**Comment by wenerme** [comment]
So, the rootfs works, thanks ! Can you also post you Dockerfile here ?

**Comment by umiddelb** [comment]
It doesn't make use of Docker, just move into the chroot environment, then:
```
apt-get update
apt-get install git make lzma sudo
git clone git://github.com/comcat/miwifi.git
cd miwifi/
make
```

**Comment by wenerme** [comment]
So, I have to setup a vm for this ? can not do this in a i386 docker container ?

**Comment by umiddelb** [comment]
Not necessarily, I just took my x64 Linux box and created the i368 root filesystem / userland in a separate directory. It's all you need. 

With OS X you will likely need to setup a VM, because you cannot execute Linux binaries under XNU/Darwin directly.

**Comment by wenerme** [comment]
Thanks, I finally build the kernel in the docker container [wener/ubuntu:r1d](https://hub.docker.com/r/wener/ubuntu). I cloned the repo in my mac, and mount to the docker will build failed, because the hfs+ is case insensitive, but if I unzip the repo in container, the kernel will build correctly.
